### PR TITLE
Wait until site exists the cloning state

### PR DESCRIPTION
**Pull request by ahegyes**
Installing SafetyNet on newly cloned sites required us to wait until the site finished cloning and SSH has been provisioned. The site cloning can take anywhere between 10-20 seconds and 5-10 minutes. 

The `create-development-site` command already waited until the site passed the `deploying` state. Now it will also wait until the site passes the `cloning` state.

This should ensure that SSH connections can always be established and SafetyNet can be installed

### CODE REVIEW

**Comment by ahegyes** [comment]
@NickGreen and @nate-allen do you guys have anything against merging this? I see Nick liked the post, so I assume you're ok with it? 😄

**Comment by nate-allen** [comment]
Yeah, it looks good to me!

**Comment by NickGreen** [comment]
I'm OK with it. I'm a little worried that someone will try to do this on a large site, and get worried that it is taking so long. On the other hand, we want Safety Net on every site, so it's probably worth it. I'd say go for it.

**Comment by ahegyes** [comment]
The other side of the coin is that we get pings from people when a big site is cloned and error messages start showing up in the terminal :)

The largest example so far is 5 minutes for a 21 GB site. If it's linear time, given that Atomic supports up to 200 GB sites, this command can take up to an hour or so ... but:

a) I doubt it's linear; cloning a few large files is likely much faster than many small ones;

b) even so, SafetyNet can't be installed unless the site finished cloning; nor anything else can be done on the site ... so we have to wait on that either way;

I'll merge this now :) Thanks for inspecting it, both of you!

**Pull request merged**
