### PR TITLE
Feature/install safety net on dev sites

### PR DESCRIPTION
**Pull request by NickGreen**
## Synopsis

Adds the Safety Net plugin to every new development site created, unless the `skip-safety-net` option is used.

## To Test

- Create a development site and verify Safety Net is loaded as an mu-plugin. e.g. `team51 create-development-site --site-id=1200878 --temporary-clone --label=nickg-safety-net-test`
- Create a development site, and skip adding Safety Net. e.g. `team51 create-development-site --site-id=1200878 --temporary-clone --label=nickg-safety-net-test --skip-safety-net`

### CODE REVIEW

**Comment by bernattorras** [comment]
I've tried these two commands and I confirm that they work as expected! 👍 

I used these commands:

- `team51 create-development-site --site-id=1251849 --temporary-clone --label=bernat-skip-safety-net-test` 

The `https://bernattorras-test-bernat-safety-net-test.mystagingwebsite.com/` site got created and **the Safety Net plugin was installed** there as a mu-plugin. The admin options page was accessible and working properly. 


- `team51 create-development-site --site-id=1251849 --temporary-clone --label=bernat-skip-safety-net-test  --skip-safety-net`

The `https://bernattorras-test-bernat-skip-safety-net-test.mystagingwebsite.com/` site got created and the **Safety Net plugin wasn't installed there**.

**Comment by nate-allen** [comment]
I can also confirm that both commands worked for me. From a code standpoint it also looks good. I think this is ready to be merged when you're ready.

**Comment by ahegyes** [comment]
> and the Safety Net plugin wasn't installed there.

@bernattorras Did you run the command using the `--dev` option? If not, for the second one, you were forcefully returned to `trunk`.

**Comment by bernattorras** [comment]
>@bernattorras Did you run the command using the --dev option? If not, for the second one, you were forcefully returned to trunk.

@ahegyes Yeah, I added the `.dev` file to the root folder to run it in dev mode and prevent it from switching to trunk. 

Thanks for the heads-up though! 😉

**Comment by ahegyes** [comment]
Ah, my bad! I see now that you were calling it using the `--skip-safety-net` option and thus it not being installed was expected behavior. I thought you were saying that it didn't install even though it was supposed to 🤦

**Pull request merged**
